version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    ports:
      - "5432:5432"

  ingress:
    build: .

    ports:
      - "8089:8089"
    environment:
      db-url: jdbc:postgresql://localhost:5432/library
      db-username: postgres
      db-password: postgres
    depends_on:
      - postgres
    restart: always
